### ISSUE TITLE
Setup 2.21 QA Environment

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#10659]
To test the KKP 2.21 release, we need a test environment that follows the alpha releases.

### Tasks

- [x] Tag first v2.21.0-alpha.0 release.
- [x] Create AWS account to host the environment.
- [x] Setup AWS-based usercluster on th captain to host the KKP setup.
- [x] Install KKP into usercluster. Enable login via Google connector for all @kubermatic.com e-mails.
- [x] Gather all relevant non-cloud datacenters
   - vCenter?
   - Openstack?
   - Equinix Metal?
- [x] Provide master/seed kubeconfig in Vault.
- [x] Create Slack channel to coordinate release/QA talks.
