### ISSUE TITLE
Fully Support of external Clusters

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#11041]
External Clusters shouldn't get treated as 2nd class citizens, we should support also the usage of

- [ ] Add templates for external clusters
- [ ] Addons (the senseful once and accessible addons)
- [ ] Applications
- [ ] OPA 
- [ ] SSH Key service
- [ ] RBAC management
- [ ] OIDC integration
- [ ] User Cluster MLA
- [ ] General MLA (alerts if external clusters have issues)
- [ ] Backups (cloud specific backups or something like velero)

**Comment by embik** [comment]
> OIDC integration

I don't believe this will be possible because we do not control the `kube-apiserver` flags on external clusters, and providers do not expose settings to configure our Dex as OIDC provider.

**Comment by csengerszabo** [comment]
@toschneck please create an order of priority from your aspect as this is a huge roadmap

**Comment by cschieder** [comment]
Removed templates and quota support as we have separate issues for them. Imo this issue should probably be split into a subissue for each point, then we can doublecheck with our devs what we already cover or have started on. Then we can add prioritities to the subissues like @csengerszabo already suggested
