### ISSUE TITLE
Test External Clusters - Test Release 2.21.2

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#11111]
### Description of the feature you would like to add / User story

Testing scenarios:
- Change: removed region from preset for EKS and region is now fetched from req instead of preset.
  - [x] Create/Import EKS cluster , choose region from the dropdown and verify if cluster is created.
- Changes made on AKS cluster and MD state:
  - [ ] Stop a aks cluster from provider side and check the status of that cluster from kkp, verify if it `Stopped`
  - [ ] Start that cluster and verify if the status is `Starting` 
  - [ ] If a aks cluster/md is in failed state(Provisioing state == failed ) then cluster/md state will show as `Warning`
- Change: GET endpoint for AKS resource groups
  - [ ] Create AKS cluster and choose the resource group  from the dropdown  and verify if cluster is created.
- [x] List of EKS Node roles while creating EKS MD.
- [ ] List of EKS ClusterServie role while creating EKS cluster.

### Solution details

- Requirement 1
- Requirement 2
- Requirement 3

**Comment by rastislavs** [comment]
closing as it was eventually not part of the 2.21.2
