### ISSUE TITLE
UI Importer (EE)

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#11328]
Umbrella Epic for the UI importer

### Description of the feature you would like to add / User story

As a KKP admin user, I would like to define or modify the Application Catalog (i.e. create or update ApplicationDefinitions for the applications) via KKP Dashboard (UI),
in order to make KKP more user friendly from applications management perspective.

### Solution details

- Provide possibility for KKP admin to define the Application Catalog (create ApplicationDefinition) via KKP Dashboard(UI).
- Provide possibility for KKP admin to modify an existing application from the Application Catalog (create ApplicationDefinition) via KKP Dashboard(UI).

### Use cases

- While working together with end users,  KKP admin can setup the Application Catalog on the fly (i.e. define or modify the application catalog from KKP Dashboard) which makes end user understand more easily what admin is doing and give quick feedback on what is expected.
- End user doesn't need to know CRDs specific to the Application Catalog.

### Additional information

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/issues/11329
- [ ] https://github.com/kubermatic/kubermatic/issues/11330
- [ ] https://github.com/kubermatic/kubermatic/issues/11331
- [ ] https://github.com/kubermatic/kubermatic/issues/11332
- [ ] https://github.com/kubermatic/kubermatic/issues/11333
```
