### ISSUE TITLE
Application catalog MVP (EE)

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12014]
### Description of the feature you would like to add / User story

As a KKP user
I would like to deploy applications to my user cluster from a internal application catalog of KKP
in order to deploy the most useful applications for software development with literally one click to k8s clusters without needing interactions with the administrator of KKP and without the need to deploy them manually on the clusters.

### Solution details

- A defined set of applications are shipped with KKP by default, so that KKP admin don't have to add these to the application catalog, and they will be already there with the KKP installation
- This MVP focuses on a narrow set of tools for providing a user cluster essential tooling for software development
- Different support levels for different shipped applications (community supported, officially supported) should show up as a parameter everywhere within the application's description
- When viewing an application description, a parameter should also show up whether the application is added by KKP admin (inhouse application) or shipped by Kubermatic (Kubermatic application)

Nice-to-haves (priority in this order):

1. New tab on Project work pane (Application Catalog) for browsing available applications in the catalog
2. New tab on Admin work pane (Applications) for browsing available applications in the catalog
3. Enable KKP Admins to add new Applications in the Admin/Manage Resources/Applications - Add new Application workflow UI

### Alternative approaches

- Adding applications to KKP installation by the KKP admin

### Use cases

- With some specific applications that are widely used, this makes the first steps easier and lowers the entry level threshold of deployment of workloads

### Roadmap
```[tasklist]
### Issues
- [ ] https://github.com/kubermatic/kubermatic/issues/12528
- [ ] https://github.com/kubermatic/kubermatic/issues/12527
- [ ] Disclaimer / Generic support template
- [ ] https://github.com/kubermatic/kubermatic/issues/12530
- [ ] https://github.com/kubermatic/kubermatic/issues/11068
- [ ] https://github.com/kubermatic/kubermatic/issues/12531
- [ ] https://github.com/kubermatic/kubermatic/issues/11328
- [ ] https://github.com/kubermatic/kubermatic/issues/12578
- [ ] Testing: writing e2e tests
```

### Shipped applications in the MVP Official catalog

```[tasklist]
### CI/CD
- [ ] Argo CD
- [ ] Flux
```
```[tasklist]
### Ingress / Networking
- [ ] MetalLB
- [ ] Nginx
- [ ] Cert-Manager
- [ ] Kube-VIP
```
```[tasklist]
### Networking
```
```[tasklist]
### Security
- [ ] Falco
- [ ] Trivy
```

**Comment by archups** [comment]
@csengerszabo @SimonTheLeg @embik As discussed and agreed, removed Cilium from the application list, since it is System application.

**Comment by archups** [comment]
@csengerszabo As discussed and agreed with @SimonTheLeg, skipping Istio for Default Application Catalog setup due to the limitation documented under https://github.com/kubermatic/kubermatic/issues/12527 (refer comments section for the details).

**Comment by csengerszabo** [comment]
@archups @SimonTheLeg FYI, I've added a `Testing: writing e2e tests` note into the Roadmap/Issues list, since this feature would need them during the testing period

**Comment by SimonTheLeg** [comment]
just fyi. I have planned some time tomorrow to write a small passage in our documentation on this feature
