### ISSUE TITLE
IPAM solution improvements

### ISSUE THREAD

**Issue by akash-gautam** [kubermatic/kubermatic#12258]
### Description of the feature you would like to add / User story

As a KKP admin, I would like some more functionalities in the IPAM solution to make it suitable for different types of environments and ensure optimal use of resources

### Use cases

- What happens if the IPAMPool I define gets completely exhausted? We can't make any modifications to the IPAMPool apart from adding & deleting data centres, if the range defined for a data centre is fully utilized, IPAMAllocation won't happen for any new cluster that gets added to it.
- As per the document deleting the IPAMPool deletes all IPAMAllocation for all the user clusters, in some cases this will lead to problems related to DNS, firewall etc as they would have been configured as per the previous allocation.
- The IPAMPool allows us to define only one continuous range of pool cidr, but the desired range might not be continuous all the time, the IPAMPool should allow specifying non-continuous ranges.
- It is also possible that for some clusters in my data centre, I don't want an IPAMAllocation to happen (because there is no network app on them) so while defining the IPAMPool there should be some option to exclude some clusters in the data centre.
- It is also possible that some clusters in a data center need more/lesser IPs than the range/prefix defined for them in the IPAMPool, having the flexibility to over-write allocation size for the cluster at the IPAMPool will be useful in the optimal use of the IP addresses.

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/issues/12381
- [ ] https://github.com/kubermatic/kubermatic/issues/12382
- [ ] https://github.com/kubermatic/kubermatic/issues/12383
- [ ] https://github.com/kubermatic/kubermatic/issues/12384
```

**Comment by toschneck** [comment]
>What happens if the IPAMPool I define gets completely exhausted? We can't make any modifications to the IPAMPool apart from adding & deleting data centres, if the range defined for a data centre is fully utilized, IPAMAllocation won't happen for any new cluster that gets added to it.

- [ ] we need an option to adding new IPs to existing configured ones, as described at https://docs.google.com/document/d/12dfGooiYGV1XeJgA-JoDNXewmUj_eV_wRMFnpE5o_ac/edit 

```
Handling Modifications to IPAMPool
If the infrastructure administrator decides to modify the `IPAMPool` from which some allocations were already made, it needs to be handled with special care - already allocated addresses should be kept whenever possible. If the `allocationRange` becomes higher, we should just allocate a new block for extra addresses that we need and create a disjoint range rather than trying to allocate a new continuous range.

Also, we should probably deny removal of a `poolCIDR` using a validation webhook, if it is still used by some clusters. To allow migrations to a new `poolCIDR`, we may introduce a `deprecated` flag, which will cause that a `poolCIDR` won’t be used for any new clusters.
```

---

> As per the document deleting the IPAMPool deletes all IPAMAllocation for all the user clusters, in some cases this will lead to problems related to DNS, firewall etc as they would have been configured as per the previous allocation.

- [ ] lets discuss with customer, how the deletion use case could get managed. Right now if IPAM pool is deleted it can't manage it anymore. If we normal have option to add new pools, we won't need to delete the existing one. We could instead you can add it to https://docs.kubermatic.com/kubermatic/v2.22/tutorials-howtos/networking/ipam/#exclusions and spec the metallb IP via addon IPAM config if you want to keep it. 

--- 

>The IPAMPool allows us to define only one continuous range of pool cidr, but the desired range might not be continuous all the time, the IPAMPool should allow specifying non-continuous ranges.

- [ x ] possible with https://docs.kubermatic.com/kubermatic/v2.22/tutorials-howtos/networking/ipam/#exclusions


---

> It is also possible that for some clusters in my data centre, I don't want an IPAMAllocation to happen (because there is no network app on them) so while defining the IPAMPool there should be some option to exclude some clusters in the data centre.

- [ ] => potential solution: label on cluster spec e.g. `ipam-controller: ignore` 
- [ ] => clarify is it really required?

---

> It is also possible that some clusters in a data center need more/lesser IPs than the range/prefix defined for them in the IPAMPool, having the flexibility to over-write allocation size for the cluster at the IPAMPool will be useful in the optimal use of the IP addresses.

- [ ] This is a given limitation, potential we could give the option per cluster spec, to allocated additional IPAMPool  junks. E.g by Default every cluster get 1 IP, if spec is changed it gets another IP junk
- [ ] Clarify easy option of implementation

**Comment by cnvergence** [comment]
I wonder if we should only limit the modification to the range type because it would be challenging with the current implementation of the prefix type to keep already allocated addresses because of the overlapping networks when changing only the allocationPrefix.
