### ISSUE TITLE
Test KKP 2.23 release

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12315]
This is a collector Epic for tasks related to testing the KKP minor release 2.23.

- We will release an alpha on the next coming days. Based on this we will conduct our tests and release additional versions as we see fit.
- Features need to be tested on all providers.
- Please create and add all your corresponding testing issues or epics to this Epic as a sub-issue.

```[tasklist]
### Testing issues
- [ ] https://github.com/kubermatic/dashboard/issues/5986
- [ ] https://github.com/kubermatic/kubermatic/issues/12321
- [ ] https://github.com/kubermatic/kubermatic/issues/12322
- [ ] https://github.com/kubermatic/kubermatic/issues/12326
- [ ] https://github.com/kubermatic/kubermatic/issues/12111
- [ ] https://github.com/kubermatic/kubermatic/issues/12336
- [ ] https://github.com/kubermatic/kubermatic/issues/12337
- [ ] https://github.com/kubermatic/kubermatic/issues/12340
- [ ] https://github.com/kubermatic/kubermatic/issues/12349
- [ ] https://github.com/kubermatic/kubermatic/issues/12351
- [ ] https://github.com/kubermatic/kubermatic/issues/12352
- [ ] https://github.com/kubermatic/kubermatic/issues/12353
- [ ] https://github.com/kubermatic/kubermatic/issues/12354
- [ ] https://github.com/kubermatic/kubermatic/issues/12355
- [ ] https://github.com/kubermatic/kubermatic/issues/12356
- [ ] https://github.com/kubermatic/kubermatic/issues/12357
- [ ] https://github.com/kubermatic/kubermatic/issues/12358
- [ ] https://github.com/kubermatic/kubermatic/issues/12359
- [ ] https://github.com/kubermatic/kubermatic/issues/12378
- [ ] https://github.com/kubermatic/kubermatic/issues/12379
- [ ] https://github.com/kubermatic/kubermatic/issues/12380
```
