### ISSUE TITLE
Improvements to the air-gapped experience for KKP setups

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12466]
This is supposed to track improvements to the user experience when setting up air-gapped environments. While it works, we have received the feedback that it could be easier.

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/issues/12368
- [ ] https://github.com/kubermatic/kubermatic/issues/12465
- [ ] https://github.com/kubermatic/docs/issues/1493
- [ ] https://github.com/kubermatic/kubermatic/issues/12310
- [ ] https://github.com/kubermatic/kubermatic/issues/12467
```
