### ISSUE TITLE
Support Kubernetes 1.28

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12563]
Kubernetes 1.28.0 has [just been released](https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/). We need support for it in KKP. Prior "art" is e.g. #12230.

Kubernetes 1.28 changelog is available [here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md).

Every task in the list below is its own issue and can be changed to one. This is just a quick placeholder so we have this in the backlog, please move tasks to separate issues once you pick this up or replace the task with the PR that fixes it.

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/pull/12570
- [ ] https://github.com/kubermatic/machine-controller/pull/1699
- [ ] https://github.com/kubermatic/operating-system-manager/pull/307
- [ ] https://github.com/kubermatic/kubermatic/pull/12593
```

**Comment by embik** [comment]
This is all done.
