### ISSUE TITLE
Backup feature for User Clusters by integrating Velero

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12646]
### Description of the feature you would like to add / User story

As a KKP User
I want to have a seamless backup solution integrated into KKP
In order to backup and restore User Clusters and data for various use cases.

### Solution details

1. **Integration of Velero:** The Velero backup solution should be seamlessly integrated into KKP, allowing users to leverage its capabilities for user cluster backups:
    - Uploads a tarball of copied Kubernetes objects into cloud object storage.
    - Calls the cloud provider API to make disk snapshots of persistent volumes, if specified.

3. **Backup Operations:** Users should be able to perform the following backup operations:
   - Create on-demand backups of user clusters or specific namespaces.
   - Schedule recurring backups of user clusters or specific namespaces.
   - Delete various backups with multiple confirmations on the UI.
   - Restore a user cluster from a backup.
   - Set up storage providers for the backups, including BackupStorageLocation and VolumeSnapshotLocation.
   - Backups should support automatic expiration, allowing users to specify a date after which the backups will be automatically deleted.

4. **Administrator level configuration**
   - At the administrator level, a "Backup" feature checkbox should be available in the Defaults and Settings plane. Disabling this checkbox should make all related UI elements inaccessible.
   - Disabling backups should not affect existing backups but should impact future functionality like scheduled jobs and manual backups.

5. **Project Owner level configuration:**
     - "Backup" work plane should be available in the navigation menu.
     - Configure multiple providers for backups and define different BackupStorageLocation and VolumeSnapshotLocation values.
     - View a list of backups for all user clusters within the project.
       - Perform batch deletion of backups with custom filtering and selection options like user cluster, date (with multiple confirmations on the UI).
       - Initiate the restoration process for backups, including the ability to select specific namespaces.
     - Create on-demand backups and schedule recurring backups, with options to set BackupStorageLocation and VolumeSnapshotLocation.
       - Configure backup expiration settings.
       - Filter namespaces during backup operations.

6. **User Cluster owner level configuration:**
   - Users should have the ability to enable or disable the backup feature at the cluster level.
   - Disabling backups for a cluster should not affect existing backups but should impact future functionality like scheduled jobs and manual backups.
   - During the creation of a user cluster, an option to enable the backup feature should be available.

### Use cases

- User cluster etcd can already be backed up and restored automatically. However, this feature is more for the platform admins and can backup only the whole etcd and nothing else (PersistentVolumes of user clusters are not backed up at all).
- Additionally if the cluster is accidentally deleted, these etc backups are deleted as well, so this isn’t fit for all disaster recovery use-cases.

### Additional information

- Velero server has to be deployed at some point on the user cluster. It cannot happen retroactively to all existing clusters
- Backup feature will only present automatically with newly created clusters where this feature is enables
- For existing clusters, you have to manually edit the cluster and enable it

### Questions
- Whether Presets can be re-used for setting up the storage providers for the backups
- Downloading (and maybe uploading) backups via the UI - we will implement this depending on the level of difficulty of the feasibility

### Non-Goals

- Supporting all features of Velero out of the KKP UI. We will determine the exact set of features that are going to be supported on the UI within the scope of this proposal.
- Supporting community maintained cloud providers of Velero.
- Managing the permissions and settings of the storage provider plugins is out of scope and has to be done directly on the providers
- Backup and restore hooks are out of scope
```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/issues/12704
- [ ] https://github.com/kubermatic/kubermatic/issues/12706
- [ ] https://github.com/kubermatic/dashboard/issues/6276
- [ ] https://github.com/kubermatic/kubermatic/issues/12828
- [ ] https://github.com/kubermatic/kubermatic/issues/12960
```
