### ISSUE TITLE
Test KKP 2.24 release

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12727]
This is a collector Epic for tasks related to testing the KKP minor release 2.24.

- We will release a beta on the next coming days. Based on this we will conduct our tests and release additional versions as we see fit.
- QA environment with beta version is also coming in the next days.
- Features need to be tested on all providers.
- Please create and add all your corresponding testing issues or epics to this Epic as a sub-issue.
```[tasklist]
### Testing issues
- [ ] https://github.com/kubermatic/kubermatic/issues/12649
- [ ] https://github.com/kubermatic/kubermatic/issues/12676
- [ ] https://github.com/kubermatic/dashboard/issues/6285
- [ ] https://github.com/kubermatic/kubermatic/issues/12741
- [ ] https://github.com/kubermatic/kubermatic/issues/12742
- [ ] #12743
- [ ] https://github.com/kubermatic/kubermatic/issues/12744
- [ ] #12745
- [ ] #12746
- [ ] #12747
- [ ] #12748
- [ ] #12749
- [ ] #12750
- [ ] https://github.com/kubermatic/kubermatic/issues/12754
- [ ] https://github.com/kubermatic/kubermatic/issues/12755
- [ ] https://github.com/kubermatic/kubermatic/issues/12759
- [ ] https://github.com/kubermatic/kubermatic/issues/12782
- [ ] https://github.com/kubermatic/kubermatic/issues/12784
- [ ] https://github.com/kubermatic/kubermatic/issues/12799
```

**Comment by embik** [comment]
Testing has completed.
