### ISSUE TITLE
Test IPAM extending allocation in IPAMPool - Test Release 2.24

### ISSUE THREAD

**Issue by cnvergence** [kubermatic/kubermatic#12759]
You can refer to the docs at https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/ipam.

Test scenario:
Apply IPAMPools with different configurations (i.e. types, pool CIDR, and allocation size) with exclusions to a user cluster datacenter.

Expected:
```[tasklist]
### Tasks
- [x] All allocations should belong to the pool subnet (i.e. poolCidr configured in the IPAMPool CR)
- [x] Allocations for same IPAMPool + datacenter + user cluster should not overlap in any allocation type (range or prefix).
```

Alter IPAMPool and increase `allocationRange` and `allocationPrefix`

Expected:
```[tasklist]
### Tasks
- [x] allocationRange change would be allowed by validation webhook
- [x] new allocation for range type would create another disjoint set of IPs in IPAMAllocation
- [x] new allocation for range type should not overlap with current allocated addresses and exclusions
- [x] allocationPrefix change would be disallowed by validation webhook
```

```[tasklist]
### Tasks
```

**Comment by cnvergence** [comment]
Apply IPAMPools on the cluster:
```bash
apiVersion: kubermatic.k8c.io/v1
kind: IPAMPool
metadata:
  name: test-prefix
spec:
  datacenters:
    azure-eastus:
      type: prefix
      poolCidr: "192.168.1.0/26"
      allocationPrefix: 30
      excludePrefixes:
      - "192.168.1.100/30"
      - "192.168.1.255/30"
---
apiVersion: kubermatic.k8c.io/v1
kind: IPAMPool
metadata:
  name: test-range
spec:
  datacenters:
    aws-eu-central-1a:
      type: range
      poolCidr: 192.168.1.0/26
      allocationRange: 10
      excludeRanges:
        - "192.168.1.1"
        - "192.168.1.5-192.168.1.7"
 ```
 Reconciled IPAMAllocations:
 ```bash
 - apiVersion: kubermatic.k8c.io/v1
  kind: IPAMAllocation
  metadata:
    generation: 1
    name: test-prefix
    namespace: cluster-lrvfphkcvb
    ownerReferences:
    - apiVersion: kubermatic.k8c.io/v1
      kind: IPAMPool
      name: test-prefix
  spec:
    cidr: 192.168.1.0/30
    dc: azure-eastus
    type: prefix
- apiVersion: kubermatic.k8c.io/v1
  kind: IPAMAllocation
  metadata:
    generation: 1
    name: test-range
    namespace: cluster-wc77qhmn9z
    ownerReferences:
    - apiVersion: kubermatic.k8c.io/v1
      kind: IPAMPool
      name: test-range
  spec:
    addresses:
    - 192.168.1.0-192.168.1.0
    - 192.168.1.2-192.168.1.4
    - 192.168.1.8-192.168.1.13
    dc: aws-eu-central-1a
    type: range
```

**Comment by cnvergence** [comment]
Updating IPAMPool test-range:
```bash
apiVersion: kubermatic.k8c.io/v1
kind: IPAMPool
metadata:
  name: test-range
spec:
  datacenters:
    aws-eu-central-1a:
      type: range
      poolCidr: 192.168.1.0/26
      allocationRange: 14
      excludeRanges:
        - "192.168.1.1"
        - "192.168.1.5-192.168.1.7"
```

New IPAMAllocation:
```bash
- apiVersion: kubermatic.k8c.io/v1
  kind: IPAMAllocation
  metadata:
    generation: 2
    name: test-range
    namespace: cluster-wc77qhmn9z
    ownerReferences:
    - apiVersion: kubermatic.k8c.io/v1
      kind: IPAMPool
      name: test-range
  spec:
    addresses:
    - 192.168.1.0-192.168.1.0
    - 192.168.1.2-192.168.1.4
    - 192.168.1.8-192.168.1.13
    - 192.168.1.14-192.168.1.17
    dc: aws-eu-central-1a
    type: range
```

**Comment by cnvergence** [comment]
Updating IPAMPool test-prefix:
```bash
apiVersion: kubermatic.k8c.io/v1
kind: IPAMPool
metadata:
  name: test-prefix
spec:
  datacenters:
    azure-eastus:
      type: prefix
      poolCidr: "192.168.1.0/26"
      allocationPrefix: 28
      excludePrefixes:
      - "192.168.1.100/28"
      - "192.168.1.255/28"
```
Resulted in:
```bash
error: ipampools.kubermatic.k8c.io "test-prefix" could not be patched: admission webhook "ipampools.kubermatic.k8c.io" denied the request: it's not allowed to update the allocation prefix for a datacenter
```
