### ISSUE TITLE
Test KKP Upgrade - Test Release 2.24

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12799]
```[tasklist]
### Tasks
- [x] Deploy master cluster with KubeOne 1.6.2 and Kubernetes 1.26.6
- [x] Deploy KKP 2.23.6 environment on KubeOne cluster for master and KKP user cluster for seed
- [x] Prepare validation (create cluster, etc)
- [x] Upgrade to KKP 2.24.0-beta.1
- [x] Validation
```

A non-exhaustive list of things that should be tested during and after an upgrade.

```[tasklist]
### To Be Validated
- [x] 1.24 and 1.25 clusters should make the upgrade fail until they are upgraded to 1.26+
- [ ] Cluster with OpenVPN for control plane connectivity still works
- [x] Azure clusters get upgraded correctly and their NSGs are simplified
- [x] Project labels are synchronized from master to seed
- [x] Kubernetes 1.24 cluster upgraded to 1.26 on 2.23 can be upgraded to 1.27 on KKP 2.24
```

**Comment by embik** [comment]
```
ERRO[0001] ⛔ Cannot proceed with the installation:
ERRO[0001]    cluster ukd5r48mng (version 1.25.14) on Seed kkp-qa-upgrade-env would not be supported anymore
ERRO[0001] ❌ Operation failed: preflight checks have failed.
```

1.25 clusters prevent the upgrade ✅

**Comment by embik** [comment]
Found #12801.

**Comment by embik** [comment]
Found #12802.

**Comment by embik** [comment]
Found #12803.

**Comment by embik** [comment]
Due to the issues above, we'll need to run another upgrade test series.

**Comment by embik** [comment]
No further issues discovered.
