### ISSUE TITLE
Improve Default Applications

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#12873]
### Description of the feature you would like to add / User story

For each of our default applications 

- Document the Apps in our docs.kubermatic.com (and show the link in our UI)
- Add the Logo 
- Provide the Link to the source of the application
- the Header should be official writing
- in the value.yaml we should provide sane defaults and also show comments  
- Link to the Application Docs 

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/issues/12937
- [ ] https://github.com/kubermatic/kubermatic/issues/12938
- [ ] https://github.com/kubermatic/docs/issues/1593
- [ ] https://github.com/kubermatic/kubermatic/issues/13330
- [ ] https://github.com/kubermatic/kubermatic/issues/12941
- [ ] https://github.com/kubermatic/kubermatic/issues/12942
- [ ] https://github.com/kubermatic/dashboard/issues/6444
- [ ] https://github.com/kubermatic/dashboard/issues/6445
- [ ] https://github.com/kubermatic/kubermatic/issues/12834
```

**Comment by csengerszabo** [comment]
Referecing a collection of reported bugs related to applications that could be attached to this: https://github.com/kubermatic/kubermatic/issues/12095

**Comment by toschneck** [comment]
Also the App should have an option to provide a link to a App sepcific documentation. cc @hc2p

**Comment by scheeles** [comment]
Agree, added
