### ISSUE TITLE
Test KKP 2.25 release

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#13016]
This is a collector Epic for any tasks related to testing the KKP 2.25 minor release

- Testing can be done on the QA environment with the 2.25 beta release
- All new features need to be tested in all possible circumstances
- Create and add all your corresponding testing issues or epics to this Epic as a sub-issue
- Don't forget about documentation during the freeze

```[tasklist]
### Testing issues - Please add them here:
- [ ] https://github.com/kubermatic/dashboard/issues/6534
- [ ] https://github.com/kubermatic/kubermatic/issues/13099
- [ ] https://github.com/kubermatic/kubermatic/issues/13022
- [ ] https://github.com/kubermatic/kubermatic/issues/13030
- [ ] https://github.com/kubermatic/kubermatic/issues/13031
- [ ] https://github.com/kubermatic/kubermatic/issues/13033
- [ ] https://github.com/kubermatic/kubermatic/issues/13034
- [ ] https://github.com/kubermatic/kubermatic/issues/13035
- [ ] https://github.com/kubermatic/kubermatic/issues/13036
- [ ] https://github.com/kubermatic/kubermatic/issues/13037
- [ ] https://github.com/kubermatic/kubermatic/issues/13038
- [ ] https://github.com/kubermatic/kubermatic/issues/13039
- [ ] https://github.com/kubermatic/kubermatic/issues/13040
- [ ] https://github.com/kubermatic/kubermatic/issues/13041
- [ ] https://github.com/kubermatic/kubermatic/issues/13042
- [ ] https://github.com/kubermatic/dashboard/issues/6491
- [ ] https://github.com/kubermatic/dashboard/issues/6483
- [ ] https://github.com/kubermatic/dashboard/issues/6479
- [ ] https://github.com/kubermatic/kubermatic/issues/13071
- [ ] https://github.com/kubermatic/kubermatic/issues/13070
- [ ] https://github.com/kubermatic/kubermatic/issues/13014
- [ ] https://github.com/kubermatic/kubermatic/issues/13101
- [ ] https://github.com/kubermatic/kubermatic/issues/13102
- [ ] https://github.com/kubermatic/kubermatic/issues/13158
```

**Comment by embik** [comment]
The equinix situation with CentOS 7 is not fully clear, but will not be a release blocker. I'll go ahead and close this ticket on account of everything else being done.
