### ISSUE TITLE
Test initial-application-controller with Cilium - Release 2.25

### ISSUE THREAD

**Issue by cnvergence** [kubermatic/kubermatic#13102]
Test adding up multiple applications during user cluster creation with Cilium as CNI.

```[tasklist]
### Tasks
- [x] Create user cluster with Cilium CNI and select two applications to be installed from the start
- [x] Verify that user cluster gets deployed
- [x] Verify that all applications are working correctly
```

**Comment by ronissac88** [comment]
Testing steps:

1. Created a user cluster sflhmwv5zm with cillium as the CNI

`sflhmwv5zm   peaceful-shannon      ronissac88@gmail.com         1.28.7    aws        aws-eu-central-1a   Running   false    75m`

```
kube-system            cilium-2kscp                                                      1/1     Running     0             63m
kube-system            cilium-54zh5                                                      1/1     Running     0             63m
kube-system            cilium-d8xmh                                                      1/1     Running     1 (62m ago)   63m
kube-system            cilium-operator-78bf8f7b4f-rtmhw                                  1/1     Running     0             68m
```

3. Deployed applications k8sgpt and metallb

4. Tested both applications and confirmed that both the applications are working correctly.
`
k8sgpt                 kube-system-k8sgpt-k8sgpt-operator-controller-manager-6574th9tl   2/2     Running     0             62m`

```
metallb                kube-system-metallb-controller-c5747479c-d4kpl                    1/1     Running     1 (61m ago)   62m
metallb                kube-system-metallb-speaker-42v54                                 4/4     Running     1 (60m ago)   61m
metallb                kube-system-metallb-speaker-djzr8                                 4/4     Running     0             62m
metallb                kube-system-metallb-speaker-ngms7                                 4/4     Running     0             62m
```
