### ISSUE TITLE
Integrate Kyverno and deprecate OPA

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#13523]
### Description of the feature you would like to add / User story

As a KKP Admin
I would like to use the features for policy management that Kyverno offers instead of OPA
in order to benefit the YAML-friendly behavior of Kyverno instead of the difficult language that OPA requires.

### Solution details

- Kyverno must be integrated on the seed level
- Default policies can be copied from KubeOne as 1.9 will contain Kyverno https://github.com/kubermatic/kubeone/issues/2453
- Setting a good default baseline is ideal
- We want to give a way to KKP admins to configure their own policies, there should be a template for policy and instances

### Additional information

- kubermatic/kubermatic#12121 is a prequisite of this epic, so Kyverno would be an enforced application on user cluster level
- Deprecation of OPA will be gradual (e.g. 2 releases co-existence)

### Tasks
- [x] https://github.com/kubermatic/kubermatic/issues/14172
- [x] https://github.com/kubermatic/kubermatic/issues/14327
- [x] https://github.com/kubermatic/dashboard/issues/7187
- [x] https://github.com/kubermatic/kubermatic/issues/14326
- [x] https://github.com/kubermatic/dashboard/issues/7006
- [x] https://github.com/kubermatic/kubermatic/issues/14234
- [x] https://github.com/kubermatic/kubermatic/issues/14383
- [x] https://github.com/kubermatic/dashboard/issues/6988
