### ISSUE TITLE
Automate addon maintenance

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13597]
Since forever, KKP has required manual effort to maintain the addon manifests. Most addons unfortunately still come with a bunch of "# please do these modifications to the upstream manifests" comments that make updating addons harder and more error prone than necessary.

In the long run we want to potentially replace addons with Applications, which are already sourced from the upstream Helm charts. However in the meantime until we're there, it would help a lot of we finally sat down and used all tools available (Kustomize, yq, sed, bash, ...) to fully automate addon updates.

```[tasklist]
### Tasks
- [ ] azure-cloud-node-manager
- [x] cluster-autoscaler
- [x] csi/aws-ebs
- [x] csi/azure-disk
- [x] csi/azure-file
- [ ] csi/azure-snapshot-controller
- [ ] csi/digitalocean
- [x] csi/gcp
- [ ] csi/hetzner
- [ ] csi/kubevirt
- [ ] csi/nutanix
- [x] csi/openstack
- [ ] csi/vmware-cloud-director
- [ ] csi/vsphere
- [x] kube-state-metrics
- [ ] node-exporter
```
