### ISSUE TITLE
Support enabling cloud drive on OpenStack VMs

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#13618]
There are two ways OpenStack VMs can access metadata: 1) metadata service, 2) config drive. The former is network/http based, the latter, as the name suggest, is a pseudo-volume attached to the VM. As such, the former is more dynamic (i.e. it reflects changes in real time) but the latter is more reliable.

However, the latter must be enabled during VM creation, but this is not currently configurable in the machine-controller.

Note that not all OpenStack installations might offer both options, metadata service and config drive.

For more information, see https://docs.openstack.org/nova/2023.2/user/metadata.html
```[tasklist]
### Tasks
- [x] Boolean config of cloud drive for OpenStack in machine-controller (https://github.com/kubermatic/machine-controller/pull/1829)
- [ ] https://github.com/kubermatic/kubeone/issues/3300
- [ ] https://github.com/kubermatic/dashboard/issues/6733
```
