### ISSUE TITLE
Test KKP 2.26 release

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13673]
This is a collector Epic for any tasks related to testing the KKP 2.26 minor release

- Testing can be done on the QA environment with the 2.26 beta release
- All new features need to be tested in all possible circumstances
- Create and add all your corresponding testing issues or epics to this Epic as a sub-issue
- Don't forget about documentation during the freeze

```[tasklist]
### Cloud Provider Support
- [ ] https://github.com/kubermatic/kubermatic/issues/13674
- [ ] https://github.com/kubermatic/kubermatic/issues/13675
- [ ] https://github.com/kubermatic/kubermatic/issues/13683
- [ ] https://github.com/kubermatic/kubermatic/issues/13682
- [ ] https://github.com/kubermatic/kubermatic/issues/13676
- [ ] https://github.com/kubermatic/kubermatic/issues/13678
- [ ] https://github.com/kubermatic/kubermatic/issues/13680
- [ ] https://github.com/kubermatic/kubermatic/issues/13677
- [ ] https://github.com/kubermatic/kubermatic/issues/13681
- [ ] https://github.com/kubermatic/kubermatic/issues/13679
- [ ] https://github.com/kubermatic/kubermatic/issues/13715
```
```[tasklist]
### Feature Testing
- [ ] https://github.com/kubermatic/kubermatic/issues/13667
- [ ] https://github.com/kubermatic/kubermatic/issues/13643
- [ ] https://github.com/kubermatic/kubermatic/issues/13623
- [ ] https://github.com/kubermatic/dashboard/issues/6811
- [ ] https://github.com/kubermatic/kubermatic/issues/13592
- [ ] https://github.com/kubermatic/kubermatic/issues/13745
- [ ] https://github.com/kubermatic/kubermatic/issues/13751
- [ ] https://github.com/kubermatic/kubermatic/issues/13752
- [ ] https://github.com/kubermatic/kubermatic/issues/13753
- [ ] https://github.com/kubermatic/kubermatic/issues/13754
- [ ] https://github.com/kubermatic/kubermatic/issues/13755
- [ ] https://github.com/kubermatic/kubermatic/issues/13756
- [ ] https://github.com/kubermatic/kubermatic/issues/13770
- [ ] https://github.com/kubermatic/kubermatic/issues/13771
- [ ] https://github.com/kubermatic/kubermatic/issues/13772
- [ ] https://github.com/kubermatic/kubermatic/issues/13774
- [x] Trivy: Check latest trivy-job for KKP and inspect for new CVEs: https://prow.loodse.com/?job=periodic-kubermatic-trivy-scan
```

```[tasklist]
### Application Testing
- [x] ArgoCD
- [x] cert-manager
- [x] Falco
- [x] flux
- [x] K8sGPT
- [x] kube-vip
- [x] KubeVirt
- [x] MetalLB
- [x] nginx-ingress-controller
- [x] NVIDIA GPU Operator
- [x] Trivy
- [x] Trivy Operator
- [ ] https://github.com/kubermatic/kubermatic/issues/13742
```

```[tasklist]
### KKP 2.25 to 2.26 Upgrade Tests
2. [ ] https://github.com/kubermatic/kubermatic/issues/13660
2. [ ] https://github.com/kubermatic/kubermatic/issues/13658
```

**Comment by toschneck** [comment]
@xrstf  / @csengerszabo 
Can we please add also a test item to test the default application's it-self.? In example the nvidia-gpu-operator was broken, see #13592

**Comment by ahmedwaleedmalik** [comment]
New ticket: https://github.com/kubermatic/kubermatic/issues/13745

**Comment by ahmedwaleedmalik** [comment]
> @xrstf / @csengerszabo Can we please add also a test item to test the default application's it-self.? In example the nvidia-gpu-operator was broken, see #13592

This is quite important as well but IMO this will need a dedicated ticket. If we add this to https://github.com/kubermatic/kubermatic/issues/13745 then it'd be unreasonable for a single person to handle this.

**Comment by dharapvj** [comment]
@csengerszabo - few more tickets added by me. Please add them to tracker above.

https://github.com/kubermatic/kubermatic/issues/13770
https://github.com/kubermatic/kubermatic/issues/13771

**Comment by cnvergence** [comment]
@csengerszabo one more added from me
https://github.com/kubermatic/kubermatic/issues/13772
