### ISSUE TITLE
Tracking issue: 2.7 release

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1582]
This issue tracks everything that must be in place/done prior to doing a Kubermatic 2.7 release

- [ ] Automatic release note generation: #1400
- [x] Pod anti affinity for the etcd statefulset #1589 
- [x] Pod disruption budged (PDB) for the etcd statefulset #1580
- [ ] Metrics server #708 
- [ ] Seed-Cluster DNS override #1358

parent of #1400
parent of #1580

**Comment by mrIncompetent** [comment]
Those are now being tracked in a milestone
