### ISSUE TITLE
Bare metal setup

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#183]
<a href="https://github.com/scheeles"><img src="https://avatars.githubusercontent.com/u/10047184?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [scheeles](https://github.com/scheeles)**
_Saturday Dec 10, 2016 at 11:44 GMT_
_Originally opened as https://github.com/kubermatic/kubermatic-internal/issues/15_

----

The general idea is to support bare metal cluster. 
We start with running servers. There should be a pool of servers ready to join the cluster. The servers boot and install a distro (which is automatically configured to connect to a cluster). After the OS is booted and the k8s components are installed, the server registers itself with our API-server as ready to join a cluster. 

When a user creates a cluster in Kubermatic, and selects “Bare-Metal” they can add nodes from the pool to this cluster. When the user adds a node, the API server sends the joining information to the Kubermatic Configuration Daemon running on the server. Now the server configures itself and when the server is ready it will register with the specified cluster.

The setup should be divided into different components. Based on the current setup of the customer he can decide, which components are required and should be installed. E.g. if the customer doesn’t want to have BMC IPMI and have an IPXE server, he can prepare and boot the server so that they are read for joining. 

 
 - IPXE Server 
 https://github.com/kelseyhightower/coreos-ipxe-server
Run on top of your seed cluster 
Can this server also serve other distros?

- DNS/DHCP/TFTP Server
DNSMASQ is probably the best option, as it is easy to configure and manage
Run on top of the seed cluster
Configured to serve `undionly.kpxe` via TFTP to PXE clients, bootstrapping IPXE

 - BCM IPMI Service (Future Feature)
Managing a pool of server, which should be ready to join the cluster
Start and stop (not joined severs) based on a threshold

- Register and configuration server 
Register a server as ready to join
Get the join information and configure the server to join as node to a cluster
Client for register the Server at the API-Server (ready to join) and configure the server

 - API Server
 Endpoint for registering (ready to join)
 Endpoint for getting the cluster information

- UI
Create and manage a bare metal cluster

- [x] https://github.com/kubermatic/dashboard-v2/issues/10 Create Cluster for Bare Metal
- [x]  https://github.com/kubermatic/dashboard-v2/issues/11 Bare Metal: Add/remove nodes to a cluster
- [x]  https://github.com/kubermatic/bare-metal-provider/issues/1 Bare Metal Provider
- [x] #197 API Integration
- [x] #198 iPXE Setup
- [x] https://github.com/kubermatic/kubelet-nanny/issues/1 Create Kubelet Nanny

**Comment by scruplelesswizard** [comment]
<a href="https://github.com/chaosaffe"><img src="https://avatars.githubusercontent.com/u/15822260?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chaosaffe](https://github.com/chaosaffe)**
_Saturday Dec 10, 2016 at 13:14 GMT_

----

The CoreOS IPXE server can serve any distro via IPXE. Unlike PXE, which uses TFTP, IPXE uses HTTP, so all it really does is serve static files. The 'magic' part is only in the generation of dynamic cloud-config files.

**Comment by scruplelesswizard** [comment]
See [kubermatic/kubelet-nanny](https://github.com/kubermatic/kubelet-nanny) and [kubermatic/bare-metal-provider](https://github.com/kubermatic/bare-metal-provider) repos
