### ISSUE TITLE
machineDeployment "Ready to be shipped" tracking issue

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2099]
This epos aims to track all remaining tasks until the machineDeployment feature is ready to be delivered in a release. Each task listed here should get an individual issue that tracks its details.

*API*

* [x] Add endpoints that manage machineDeployments
  * [x] #2212 creating `MachineDeployment`
  * [x] #2453 Update a `machineDeployment`
  * [x] #2213 listing `MachineDeployment`s
  * [x] #2214 getting a `MachineDeployment`
  * [x] #2215 deleting a `MachineDeployment`
* [x] Change the existing node endpoints to now show machines/nodes that are owned by a machineSet (#2216)
* [x] Change the existing node endpoints to only allow GET and DELETE and return a helpful error if other operations are attempted (#2217)

*UI*

* [x] Show machineDeployments
* [x] Discuss and implement how a machineDeployments status can be displayed
  * [ ]   Do we want to show individual machineSets and their configuration?
* [x] Allow updating machineDeployments
* [x] Continue to show machines and allow deleting them, but not creation of new ones
  * [x] Maybe implement this in a backwards-compatible way by checking if the API exposes the machineDeployment endpoint?

*Controllers*

* [x] Add mutatingAdmissionWebhok to machine-controller: kubermatic/machine-controller#227
* [x] Add the defaulting and validation from the upstream cluster-api project to that webhook
* [x] Move the existing defaulting and validation out of the machine-controller and into that webhook
* [x] Do the existing defaulting and validation at the highest possible level and only once (e.G. do it at machineDeployment level and not do it again for each individual machine)
* [x] Make the machine-controller drain nodes before it deletes machines: kubermatic/kubermatic#2158
