### ISSUE TITLE
Setup Prow

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#2123]
### User Story

To setup prow and start using prow plugins and Tide for merge automation and prowjobs for testing.

### Acceptance criteria

- [x] Test a prow setup before enabling on Kubermatic repos. Test setup is here: https://github.com/prowtest/prow-test-2.
- [x] Add `plugins.yaml` file for describing the enabled plugins (https://github.com/kubermatic/infra/pull/21)
- [x] Add `config.yaml` for describing Tide configuration (https://github.com/kubermatic/infra/pull/22)
- [x] Add manifest files containing all the necessary resources to deploy various prow components (https://github.com/kubermatic/infra/pull/22)
- [x] Check back with upstream about how much resources is needed in terms of cpu and memory. Ref: https://github.com/kubermatic/infra/pull/22#pullrequestreview-163806196
- [x] Set up a URL for the prow dashboard (maybe prow.kubermatic.io). Example of the upstream dashboard: https://prow.k8s.io/.
- [x] Configure SSL.
- [x] Deploy prow to the machine-controller and DO provider repos initially.
- [x] We have documentation of how secret management for jobs works with prow.
  - [Script](https://github.com/kubermatic/infra/blob/master/prow/hack/vault-extract-secrets.sh) has been added, but proper docs for it still need to be added.

#### For prow to be usable for machine-controller

- [x] We have a [webapp](https://github.com/kubermatic/tail) for showing logs from the bucket.
- [x] Prow is configured to display a correct link (ref: https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L2)
- [x] It is verified, that for external contributions the `needs-ok-to-test` label gets applied, blocks tests from being executed and can be removed by members.
- [x] All existing ci jobs are moved over from circleci to prow for machine-controller

#### For prow to be usable for private repos
-  [x] To  build a simplistic webapp, as we need to perform access control based on repo which Gubernator can't do (And its also not possible to put a proxy in front of it, as its an appengine-based app)
    - PR open: https://github.com/kubermatic/tail/pull/4.
- [ ] Add prowjobs for all private repos.
- [x] Verify that only members of the org can view these logs.
- [ ] All existing ci jobs are moved over from circleci to prow for private repos.

**Comment by nikhita** [comment]
Closing this in favour of https://github.com/kubermatic/kubermatic/issues/2520.
