### ISSUE TITLE
Extend Kubermatic Labeling: Projects -> Cluster -> Node

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#3717]
Customer Request: https://github.com/kubermatic/customer-projects/issues/57

**User Story**
Kubermatic need to get the possibility to apply Labels on multiple stages:

1. Project labels
2. Cluster labels
3. Machine / Node labels (already present)

Additional to this the following requirement's are needed:
- Labels get inherited from Project -> Cluster -> Machine -> Node, e.g. a node object, could then hold:
```
kubermatic/project: project-1
kubermatic/cluster: cluster-id-xyz
kubermatic/custom-node-label: awesome-node
```
- ~Add an regex based validation for mandatory labels, e.g. a cost center ID~
  - at least for project level, but maybe a generic approach make sense
  - They can use admission control. -- Kamil

**Acceptance criteria**
- [ ] Project, Cluster can get enforced to specify some labels over the UI
- [ ] ~Kubermatic config could specify mandatory labels with regex~
- [ ] Labels get inherited between Projects, Cluster, Machine, Nodes

**Comment by alvaroaleman** [comment]
What is "labels"? Kubernetes labels? Labels on AWS resources?

Should the enforcing mechanism be statically configured or via the UI (Your AC says both) or both? If via the UI, how do we determine if a user is allowed to specify such a requirement?

**Comment by toschneck** [comment]
@alvaroaleman in this issue only would reference Kubernetes labels on the different Kubernetes objects. The handling for AWS tags is described here #3755.

> Should the enforcing mechanism be statically configured or via the UI (Your AC says both) or both? If via the UI, how do we determine if a user is allowed to specify such a requirement?

The enforcing mechanism for labels should only be configurable by the static Kubermatic backend config. At the UI level the user only can add additional labels, but the enforced labels need to filled out and match the regex from the backend configuration.

**Comment by kdomanski** [comment]
@toschneck I think the purpose of Kubernetes object labels is not to be part of business logic, much less a specific customer's workflow. We should add dedicated tag fields to cluster and project objects and then make them inherited at every stage. The existing `system/project` and `system/cluster` tags would be then be applied by default in their respective project/cluster and then inherited.

@alvaroaleman WDYT

**Comment by toschneck** [comment]
sounds also ok, can you maybe share upfront a sketch of the UI dialog? - so that I can tell you more if this is the direction we wanted to go.

> would be then be applied by default in their respective project/cluster and then inherited.
@kdomanski the get inherited  to AWS resources and Kubernetes node objects right?
- AWS TAGS are needed for the customer to use the AWS billing functions 
- Kubernetes Node Labels, are used for the Kubermatic metering tool

Nevertheless we need also a possibility to validate the entry values against e.g. a regex expression.

**Comment by toschneck** [comment]
@kdomanski any update on this?

**Comment by toschneck** [comment]
Currently not working like expected: https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/kubermatic/4433#issuecomment-542933522

**Comment by alvaroaleman** [comment]
@toschneck please discuss your issues with #4433 in #4433 and do not re-open other issues.
/close
