### ISSUE TITLE
Use external CCM with vsphere

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#5320]
**User Story**
Analogous to #4610, but for vsphere

**Acceptance criteria**
- [ ] https://github.com/kubernetes-sigs/vsphere-csi-driver is used for new clusters instead of the in-tree provider

**Comment by mlavacca** [comment]
/reopen 
since the main issue is addressed, but the following additional work needs to be done yet:
- [ ] once machine-controller will be released, update it to that version to bring in the cluster-id field in the vSphere cloud-config.
- [ ] add e2e tests.
- [ ] allow the user to provide the needed VM Storage Policy, and create a StorageClass based on it.
- [ ] document how to set everything up
