### ISSUE TITLE
Etcd Operation Improvement

### ISSUE THREAD

**Issue by moelsayed** [kubermatic/kubermatic#5541]
This epic is for tracking the planned improvements for how we managed etcd in user clusters.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/5541).

The main requirements are:
- [x] Automated backup restore.
- [x] Add ability to resize (up/down) the etcd cluster.
- [x] Disaster recovery from lost node/volumes. 
- [x] Storage class migration.
