### ISSUE TITLE
Presets Management

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6123]
**User Story**
The admin user can add and manage the kubermatic presets in the UI.

- create an endpoint to add presets
- create endpoints to manage presets (get, list, delete)

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/6123).

**Comment by floreks** [comment]
As discussed with @zreigz we'll not be introducing `delete` endpoint just yet as it would require major changes of the controllers and a bigger discussion. Instead, we'll add `enabled` field to preset and preset providers to allow filtering out disabled presets without having to manage and sync connected credential secrets.

#### Acceptance criteria
##### API
- [x] List presets for all providers
  - [x] Filter by enabled status
- [x] List presets for selected provider
  - [x] Filter by datacenter
  - [x] Filter by enabled status
- [x] Create a preset for the provider
- [x] Update existing provider preset
  - [x] Enable/disable preset or a specific provider for the preset
  - [x] Update/remove datacenter restriction

##### UI (https://github.com/kubermatic/dashboard/issues/2798)
- Manage preset creation/edition from the admin panel

**Comment by floreks** [comment]
Finished
