### ISSUE TITLE
API Openstack field "tenant" is deprecated name

### ISSUE THREAD

**Issue by furkhat** [kubermatic/kubermatic#6248]
"tenant" is deprecated in OpenStack. This is what is included in the "OpenStack RC File v3". Can we rename it to "project" or "os_project"?

**Comment by furkhat** [comment]
nope still true /remove-lifecycle stale

**Comment by vgramer** [comment]
- [ ] update machine-controller to handle project auth vars -> kubermatic/machine-controller#1091
- [ ] bump machine controller in KPP
- [ ] update KPP to handle project auth vars 
- [ ] update dashboard
