### ISSUE TITLE
Add endpoints for all kind of provider fields.

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#6360]
Use provider api to get all provider related fields - if possible (haven't checked all, yet). The user then will have the possibility to choose from a dropdown. Entering on their own via Input field should be also possible.

Strike through if not possible:

**AWS:**
- [ ] Security Group ID
- [ ] ~Route Table ID~
- [ ] ~Instance Profile Name~
- [ ] ~Control plane role (ARN)~
- [ ] ~AMI ID~

**Azure:**
- [ ] Resource Group
- [ ] Route Table
- [ ] Security Group
- [ ] Subnet
- [ ] VNet

**GCP:**
- [x] Network
- [x] Subnetwork

**Comment by kgroschoff** [comment]
Short update for AWS:

- **Security Group ID**
  Definitely a dropdown. 
  Could be a very long list -> Filter option makes sense.
  Should be filtered per VPC -> Only selectable if VPC is specified.
  Provide `Name` in Dropdown, if available.
  Not required. If not specified, a new security group will be created via backend.
  **Attention:** Better placed in Node Deployment Spec than in Cluster Spec. No issue yet.

- **Route Table ID**
  ~TBD: Might be not necessary anymore. Will update if there are news.~
  ~In case should still be in UI, it is useful to have a dropdown.~
  ~Should be filtered per VPC -> Only selectable if VPC is specified.~
  Not needed anymore. Related issue: https://github.com/kubermatic/kubermatic/issues/4984

- **Instance Profile Name**
  No dropdown needed atm, maybe in the future as it's more about roles.
  **Attention:** Better placed in Node Deployment Spec than in Cluster Spec. Related Issue: https://github.com/kubermatic/kubermatic/issues/4211

- **Control Plane Role (ARN)**
  No dropdown needed atm. 
  **Wishlist:** It would be nice to have a direct verification, if the input is valid (before clicking `Create Cluster` and getting Errors from the API).

- **AMI ID**
  Probably no dropdown needed atm, as you could add AMIs on your own (dropdown might be nice for those) or just use the ones from the marketplace (dropdown might get extremely long).
  **Wishlist:** It would be nice to have a direct verification, if the input is valid (before clicking `Create Cluster` and getting Errors from the API).

**Comment by kgroschoff** [comment]
Update for Azure:

- All fields rely on the `VNet`, therefor they are not selectable, until the `VNet` is chosen.
- Move the `VNet` field to first position in the `Extended Options` area, as it is "required" (not required for cluster creation itself) for all the other options.

**Comment by kdomanski** [comment]
crossref https://github.com/kubermatic/kubermatic/issues/4473

**Comment by kdomanski** [comment]
This requires some tickets in https://github.com/kubermatic/kubermatic for specific endpoints.

**Comment by maciaszczykm** [comment]
I've moved this epic from the dashboard repo as this is about adding new endpoints. I'll create separate epic for the dashboard right now.
