### ISSUE TITLE
Release 2.16

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6439]
### Tasks

This issue tracks the individual steps for a new KKP minor release.

#### Dashboard

* [x] create `release/vX.Y` branch
* [x] in `master` branch, update `Makefile`, change `HUMAN_VERSION` to `X.(Y+1)`
* [x] adjust Prowjobs, milestone plugin config
* [x] create `vX.Y` tag
* [x] create new GitHub milestone on https://github.com/kubermatic/dashboard/milestones

#### KKP

* [x] create `release/vX.Y` branch
* [x] adjust Prowjobs, milestone plugin config
* [x] create `vX.Y` tag
* [x] create new GitHub milestone on https://github.com/kubermatic/kubermatic/milestones
* [ ] update changelog in `master` branch using gchl

#### Documentation

* [x] duplicate `content/kubermatic/master/` as `content/kubermatic/vX.Y`, including static assets and others (scattered throughout the docs repository); adjust content to make sure relative links and images work
* [x] update `data/products.yaml` with the new version

#### Post-Release

* [x] run conformance-tests for all supported Kubernetes versions, publish results in https://github.com/cncf/k8s-conformance/

### Acceptance criteria

- [x] KKP 2.16 CE is available.
- [x] KKP 2.16 EE is available.

**Comment by kron4eg** [comment]
@xrstf this looks like it's done

**Comment by xrstf** [comment]
No, the conformance tests have not been run yet, we're not yet certified.

**Comment by xrstf** [comment]
Conformance results have been submitted to the CNCF, let's wait: https://github.com/cncf/k8s-conformance/pulls/xrstf

**Comment by xrstf** [comment]
Conformance tests accepted, release is complete now.
