### ISSUE TITLE
Release of KKP 2.17

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6886]
This meta issue tracks all the work items necessary for the release of KKP.

At a high level the following tasks must be completed:

- [x] Make sure that the default supported versions are up to date (see [source code](https://github.com/kubermatic/kubermatic/blob/5b7a9dfde744b0d91e40e5547271595e6803559d/pkg/controller/operator/common/defaults.go#L193-L313))
- [x] Run all conformance tests (including optional) ensuring that the newly introduced k8s minor version is coverd.
- [x] Release a pre-release (alpha, beta) version of Kubermatic dashboard for testing ( see [release process](https://github.com/kubermatic/dashboard/blob/400fa5cfb6632dc65223fc74aaefc53dcd55f393/docs/manuals/release.md))
- [x] Release a pre-release (alpha, beta) version of Kubermatic components for testing ( see [release process](https://github.com/kubermatic/kubermatic/blob/5b7a9dfde744b0d91e40e5547271595e6803559d/docs/release-process.md))
- [x] Prepare branch with the documentation for the new release
- [x] Draft release notes for the version
- [x] Upgrade the QA platform to the new release for manual testing
- [x] Identify and fix bugs and iterate to pre-release until no major problems are identified
- [x] Make sure documentation is up-to-date (verify if new features are covered) and integrate documentation in the master branch
- [x] Release stable version
