### ISSUE TITLE
Make Tunneling expose strategy generally available

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#7125]
**User Story**

The goal of this task is to make the tunneling expose strategy generally available. The following points should be addressed:

- [x] Replace the script that creates the dummy interface with a binary.
- [ ] Expose and scrape agent metrics.
- [x] Allow customization of the agent IP (192.168.30.10).
- [ ] (Investigation needed) Support environments with enterprise proxies.
- [ ] (Investigation needed) Consider not deploying an agent per worker node (i.e. use a deployment).
- [ ] (Optional) Consider using Cilium [Local Redirect Policy](https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/) to steer traffic to envoy-agent when Cilium CNI is used.
- [x] Remove the feature gate

**Acceptance criteria**

Make sure the aforementioned points have been addressed.

**Comment by rastislavs** [comment]
Tunneling made GA in https://github.com/kubermatic/kubermatic/pull/11680
The remaining enhancements will be tracked separately.
