### ISSUE TITLE
Production-ready Cilium CNI on KKP

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#7870]
As part of https://github.com/kubermatic/kubermatic/issues/7577 Cilium has been integrated as an alternative CNI  for KKP.
The aim of this epic is to track tasks for making it production-ready:

- [x] Hubble Relay & UI integration
- [ ] Provide cluster API options for enabling advanced Cilium features (e.g. bandwidth-manager, load-balancer algorithm etc.) 
- [x] Investigate failing Cilium connectivity tests
- [x] Investigate failing k8s conformance tests
- [x] Provide migration path for clusters with Canal
- [ ] Document CNI options in KKP

**Comment by rastislavs** [comment]
Docs will be updated as part of https://github.com/kubermatic/kubermatic/issues/8539

Options for enabling/disabling several features in CIlium CNI will be done as part of https://github.com/kubermatic/kubermatic/issues/8540
