### ISSUE TITLE
Create ApplicationInstallationController

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#8384]
**Acceptance Criteria**
* ensure that each user cluster has its separate ApplicationInstallationController
* ApplicationInstallationController can receive on ApplicationInstallations events (simple printf("ApplicationInstallation xyz has been created") is sufficient)

**Implementation Hints**
* during the app proposal we came to the conclusion that the ApplicationInstallationController should live in the seed cluster in the namespace that belongs to the corresponding user-cluster

**tasks**:
*These tasks were implemented in a bigger PR(#9313)but to facilitate the review, it split in smaller pr*
- [x] update the ApplicationInstallation status to store that applicationVersion used to install /uninstall the application. (#9417)
- [x] install applicationInstallationCR into user-cluster (#9418)
- [x] simple applicationInstallation Controller that enqueue ApplicationInstallation For ApplicationDefition (#9500)
- [x] implement logic to call ApplicationInstaller (#9559)

**Comment by dermorz** [comment]
I added the open questions to the issue description:
>**Open questions**
>* Where does the ApplicationInstallationController live? Will it be part of the user-cluster-controller-manager or should it be a stand-alone controller like the machine-deployment-controller? (-> add reference to research story here)

We need to answer these questions before we can continue estimating.
