### ISSUE TITLE
Make Konnectivity generally available

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8536]
As part of https://github.com/kubermatic/kubermatic/issues/6188, [Konnectivity](https://github.com/kubernetes-sigs/apiserver-network-proxy) has been added as an alternative solution for control plane to cluster network communication (replacement of the KKP-specific OpenVPN solution). The feature is kept under the `KonnectivityService` feature gate in the `KubermaticConfiguration`.

The goal of this task is to make Konnectivity generally available. The following points should be addressed:

- [x] Create e2e tests for Konnectivity
- [x] Test Konnectivity on all supported cloud providers, k8s versions and expose strategies
- [x] Resolve potential issues with scaling apiserver (https://github.com/kubermatic/kubermatic/issues/8701)
- [x] the `KonnectivityService` feature gate should be removed and Konnectivity should be enabled by default for all new KKP clusters
- [ ] OpenVPN should be deprecated and the KKP users should be asked to migrate to Konnectivity (in docs / KKP UI)

**Comment by almereyda** [comment]
Thank you for the follow up issue. As a side note, as it's nothing, but the link to `Konnectivity` above was probably intended to target at `https://github.com/kubernetes-sigs/apiserver-network-proxy`, instead of the currently broken link.

Feel free to hide/remove my comment at any time.

**Comment by rastislavs** [comment]
Postponing the last step (removing Konenctivity feature gate and making it enabled by default) until a later KKP release due to the upstream issues (mainly resource leaks).

**Comment by RuriRyan** [comment]
Have you actually tested this? From my experience and running konnectivity since a couple years now, we never encountered such an issue. And when something like this happened it was a misconfiguration of a cluster, of course not nice, but at least fixable.

**Comment by rastislavs** [comment]
> Have you actually tested this? From my experience and running konnectivity since a couple years now, we never encountered such an issue.

@RuriRyan Yes, in some specific environments we were hitting issues with konenctivity-server running out of memory. It was quite rare, most likely triggered by specific networking conditions, but it happened.

That said, there have been several fixes on this front lately in upstream, and so far it seems they helped, so we will most likely proceed with making Konenctivity default in the next KKP release.

**Comment by rastislavs** [comment]
GA in 2.22
