### ISSUE TITLE
Update KKP Networking Documentation

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8539]
Update KKP Networking Documentation to include:

- [ ] List of supported CNIs and how to select them
- [ ] CNI-specific documentation (e.g. Cilium + ebpf, CIlium + Hubble)
- [ ] CNI version upgrade options & rules
- [ ] Manual migration between different CNIs (e.g. Canal -> Cilium)
- [ ] Konnectivity - how to enable it, switching between Konenctivity & OpenVPN
