### ISSUE TITLE
Enhance Multus integration with KKP

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8878]
The aim of this story is to enhance Multus integration with KKP:
 - [ ] Update the version
 - [ ] Make it easier to install / enable in the user cluster without the need for manual multus-cni-config ConfigMap creation
 - [ ] Make sure it works fine with CNIs supported by KKP (e.g. address Cilium modifications of `/etc/cni/net.d` upon each cilium pod start)
 - [ ] Update documentation accordingly
