### ISSUE TITLE
Dual-stack support for AWS clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9100]
Add dual-stack support for KKP user-clusters in AWS:

- [x] Investigate dual-stack capabilities of AWS
- [x] Add dual-stack support for KKP-managed AWS configuration
- [x] Add dual-stack support for AWS in machine-controller
- [x] Enhance API endpoints for listing dual-stack VPCs and subnets in AWS
- [x] Analyse / enhance AWS CCM support for IPv6
- [x] Filter out subnets that don't have both CIDRs (IPV4 and IPV6) if "dual stack" is selected in AWS
