### ISSUE TITLE
Dual-stack support for GCP clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9350]
Add dual-stack support for KKP user-clusters on this cloud provider:

- [x] Investigate dual-stack capabilities of the provider
- [x] Add dual-stack support for KKP-managed cloud-provider configuration
- [x] Add dual-stack support for the cloud-provider in machine-controller
