### ISSUE TITLE
Dual-stack support for VMware vSphere clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9360]
Add dual-stack support for KKP user-clusters on this cloud provider:

- [ ] Investigate dual-stack capabilities of the provider
- [ ] Add dual-stack support for KKP-managed cloud-provider configuration
- [ ] Add dual-stack support for the cloud-provider in machine-controller
